FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps
COPY . .
EXPOSE 5173
# Čist Node, bez Nginxa, direktno dižemo Vite
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]